
spring:
  application:
    name: bank-gateway-server
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
        routes:
          - id: kyc
            uri: http://localhost:8004
            predicates:
            - Method=GET,POST,PATCH
            - Path=api/kyc
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: prod
---